/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_my_add.check" instead.
 */

#include <check.h>

#line 1 "test_my_add.check"
#include "../my_add.h"

START_TEST(add)
{
#line 4
  fail_unless(my_add(0, 0) == 0, "sum function borked");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, add);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
